"""
Backtesting Engine
══════════════════
Validates StockGuru signals against 1-year historical Yahoo Finance data.

How it works:
  1. Load signal_history.json (past signals generated by agents)
  2. For each signal: fetch historical price data around the signal date
  3. Simulate: did price hit Target 1? Stop Loss? Still open?
  4. Calculate performance metrics: win rate, Sharpe, drawdown, avg R:R

Also runs "synthetic backtests" using current watchlist rules
applied to 252 days of historical data (1 trading year).
"""

import os
import json
import logging
import requests
from datetime import datetime, timedelta
from collections import defaultdict

log = logging.getLogger("Backtesting")

_BASE = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
SIGNAL_HISTORY_PATH = os.path.join(_BASE, "data", "signal_history.json")
RESULTS_PATH        = os.path.join(_BASE, "data", "backtest_results.json")


class BacktestEngine:

    def __init__(self):
        self.signal_history = self._load_signal_history()

    def _load_signal_history(self) -> list:
        try:
            with open(SIGNAL_HISTORY_PATH) as f:
                return json.load(f)
        except Exception:
            return []

    def _fetch_history(self, symbol: str, days: int = 90) -> list:
        """
        Fetch OHLCV history from Yahoo Finance (no API key).
        Returns list of {"date", "open", "high", "low", "close", "volume"}.
        """
        end   = datetime.now()
        start = end - timedelta(days=days)
        url   = (
            f"https://query1.finance.yahoo.com/v8/finance/chart/{symbol}"
            f"?interval=1d&period1={int(start.timestamp())}&period2={int(end.timestamp())}"
        )
        try:
            r = requests.get(url, headers={"User-Agent": "Mozilla/5.0"}, timeout=10)
            data = r.json()
            result_data = data["chart"]["result"][0]
            timestamps  = result_data["timestamp"]
            closes      = result_data["indicators"]["quote"][0]["close"]
            highs       = result_data["indicators"]["quote"][0]["high"]
            lows        = result_data["indicators"]["quote"][0]["low"]
            opens       = result_data["indicators"]["quote"][0]["open"]
            bars = []
            for i, ts in enumerate(timestamps):
                if closes[i] is None:
                    continue
                bars.append({
                    "date":  datetime.fromtimestamp(ts).strftime("%Y-%m-%d"),
                    "open":  round(opens[i] or 0, 2),
                    "high":  round(highs[i] or 0, 2),
                    "low":   round(lows[i] or 0, 2),
                    "close": round(closes[i] or 0, 2),
                })
            return bars
        except Exception as e:
            log.debug(f"History fetch error for {symbol}: {e}")
            return []

    def _simulate_trade(self, entry: float, target: float, stop_loss: float,
                        bars_after_entry: list, max_hold_days: int = 20) -> dict:
        """
        Simulate a trade outcome given price bars starting from entry day.
        Returns outcome dict.
        """
        if not bars_after_entry or entry <= 0:
            return {"outcome": "UNKNOWN", "hold_days": 0, "pnl_pct": 0}

        for i, bar in enumerate(bars_after_entry[:max_hold_days]):
            # Check if stop loss hit (use low of candle)
            if bar["low"] <= stop_loss:
                pnl_pct = round((stop_loss - entry) / entry * 100, 2)
                return {
                    "outcome":   "SL_HIT",
                    "hold_days": i + 1,
                    "exit_price": stop_loss,
                    "pnl_pct":   pnl_pct,
                    "rr_achieved": 0
                }
            # Check if target hit (use high of candle)
            if bar["high"] >= target:
                pnl_pct = round((target - entry) / entry * 100, 2)
                potential_loss = abs(entry - stop_loss)
                rr = round(abs(target - entry) / potential_loss, 2) if potential_loss > 0 else 0
                return {
                    "outcome":    "TARGET_HIT",
                    "hold_days":  i + 1,
                    "exit_price": target,
                    "pnl_pct":    pnl_pct,
                    "rr_achieved": rr
                }

        # Still open after max_hold_days
        last_close = bars_after_entry[min(max_hold_days - 1, len(bars_after_entry) - 1)]["close"]
        pnl_pct    = round((last_close - entry) / entry * 100, 2)
        return {
            "outcome":   "EXPIRED",
            "hold_days": max_hold_days,
            "exit_price": last_close,
            "pnl_pct":   pnl_pct,
            "rr_achieved": 0
        }

    def run_signal_backtest(self, lookback_signals: int = 50) -> dict:
        """
        Backtest the last N signals from signal_history.json.
        """
        signals = self.signal_history[-lookback_signals:]
        if not signals:
            return {"error": "No signal history found. Run agents first to generate signals."}

        results = []
        wins = losses = unknowns = 0
        total_pnl = 0
        sector_results = defaultdict(lambda: {"wins": 0, "losses": 0, "total": 0})

        for sig in signals:
            symbol  = sig.get("symbol", "")
            entry   = float(sig.get("entry", sig.get("price", 0)) or 0)
            target  = float(sig.get("target", 0) or 0)
            sl      = float(sig.get("sl", sig.get("stop_loss", 0)) or 0)
            sector  = sig.get("sector", "Unknown")
            sig_date = sig.get("date", sig.get("timestamp", ""))

            if not (symbol and entry and target and sl):
                continue

            # Fetch historical data around signal date
            bars = self._fetch_history(symbol, days=90)
            if not bars:
                unknowns += 1
                continue

            # Find bars after signal date
            bars_after = [b for b in bars if b["date"] >= sig_date[:10]] if sig_date else bars

            outcome = self._simulate_trade(entry, target, sl, bars_after)
            outcome["symbol"] = symbol
            outcome["sector"] = sector
            outcome["signal_score"] = sig.get("score", sig.get("conviction", 0))

            results.append(outcome)
            total_pnl += outcome.get("pnl_pct", 0)
            sector_results[sector]["total"] += 1

            if outcome["outcome"] == "TARGET_HIT":
                wins += 1
                sector_results[sector]["wins"] += 1
            elif outcome["outcome"] == "SL_HIT":
                losses += 1
                sector_results[sector]["losses"] += 1
            else:
                unknowns += 1

        total_decided = wins + losses
        win_rate = round(wins / total_decided, 3) if total_decided > 0 else 0

        # Sharpe ratio (simplified: mean return / std of returns)
        pnl_list = [r["pnl_pct"] for r in results if r.get("pnl_pct") is not None]
        if len(pnl_list) >= 2:
            import statistics
            mean_ret = statistics.mean(pnl_list)
            std_ret  = statistics.stdev(pnl_list)
            sharpe   = round(mean_ret / std_ret * (252 ** 0.5), 2) if std_ret > 0 else 0
        else:
            sharpe = 0

        # Max drawdown
        cumulative = 0
        peak = 0
        max_dd = 0
        for pnl in pnl_list:
            cumulative += pnl
            peak = max(peak, cumulative)
            dd = peak - cumulative
            max_dd = max(max_dd, dd)

        sector_summary = {
            sec: {
                "win_rate": round(v["wins"] / v["total"], 2) if v["total"] > 0 else 0,
                **v
            }
            for sec, v in sector_results.items()
        }

        result = {
            "run_date":        datetime.now().strftime("%d %b %Y %H:%M"),
            "signals_tested":  len(results),
            "wins":            wins,
            "losses":          losses,
            "unknowns":        unknowns,
            "win_rate":        win_rate,
            "avg_pnl_pct":     round(total_pnl / len(results), 2) if results else 0,
            "sharpe_ratio":    sharpe,
            "max_drawdown_pct": round(max_dd, 2),
            "by_sector":       sector_summary,
            "last_20_trades":  results[-20:],
        }

        # Save results
        try:
            with open(RESULTS_PATH, "w") as f:
                json.dump(result, f, indent=2)
        except Exception:
            pass

        log.info(
            f"Backtest: {len(results)} signals | Win rate: {win_rate:.1%} | "
            f"Sharpe: {sharpe} | Max DD: {max_dd:.1f}%"
        )
        return result

    def load_results(self) -> dict:
        """Load the last saved backtest results."""
        try:
            with open(RESULTS_PATH) as f:
                return json.load(f)
        except Exception:
            return {}
